### ISSUE TITLE
Pandas Error:

### ISSUE THREAD

**Issue by pajmera** [TabViewer/tabview#155]
Hi,

I am using pandas 0.22 version.

Trying to use following code so as to understand how tabview is used/visible

>>>>>>>>
import pandas as pd
import numpy as np
import tabview.tabview as t
from tkinter import *

def view(data):
    if isinstance(data, pd.DataFrame) or isinstance(data, pd.Series):
        result = t.view(data.reset_index().transpose().reset_index().transpose().values)
        return(result)
    elif isinstance(data, pd.Panel):
        result = t.view(panel.to_frame().reset_index().transpose().reset_index().transpose().values)
        return(result)
    else:
        raise(NotImplementedError)

df_test = pd.DataFrame({"a": [1,2,3,4,5], "b": [2,3,4,5,6]})
print(df_test)

view(df_test)

>>>>>>>>>>>>>>>

But, I am getting following error/ traceback

Traceback (most recent call last):
  File "/Users/pradeepajmera/Documents/Pradeep/Personal/Python/MyCodes/DataFrame_Viewer_Using_TabView_bug.py", line 19, in <module>
    view(df_test)
  File "/Users/pradeepajmera/Documents/Pradeep/Personal/Python/MyCodes/DataFrame_Viewer_Using_TabView_bug.py", line 8, in view
    result = t.view(data.reset_index().transpose().reset_index().transpose().values)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tabview/tabview.py", line 1368, in view
    if new_data:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Can you help me to identify/resolve error?

Thanks,

**Comment by firecat53** [comment]
This one-liner works for your test case... hopefully it sheds some light on making it work for more complex cases! Tabview doesn't read Pandas data frames directly, so that needs to be converted to some kind of tabular data (a list of lists, or a csv string like in this example).
    
    import tabview as t  # Notice the change from your import above
    t.view(df_test.to_csv().encode().split(b"\n"))

I'm sure there's a better way...I'm just not familiar with Pandas!

**Comment by wavexx** [comment]
On Tue, Feb 20 2018, pajmera wrote:
> df_test = pd.DataFrame({"a": [1,2,3,4,5], "b": [2,3,4,5,6]})
> print(df_test)
>
> view(df_test)

tabview will try to use df_test as a nested lists, and there are
multiple ways where this could/will fail.

The quickest way to show a DF in tabview is to force a conversion:

  view( list(df_test.values) )

which should work in most cases.

Resetting the index as you did before can also be necessary if you want
to see that information, as "values" can be meaningless otherwise.

"gtabview" has proper support for all pandas/numpy types. But that shows
a separate data window so that depends on what you need.

Spyder now also has most of the code from gtabview as well to display
pandas data types.

**Comment by firecat53** [comment]
@pajmera, did we answer you questions?

**Comment by JPFrancoia** [comment]
@firecat53 , the solution you provided worked for me.

Tabview is really cool, and I think my use case is the same as @pajmera : scroll a pandas dataset.

The point is to browse the dataset from the command line (ipython) and not have to deal with any Jupyter BS.

Do you think you could add some pandas integration? I'm sure it would benefit a lot of people out there, since data science is really trendy.

**Comment by saulpw** [comment]
@JPFrancola, have also you seen https://github.com/saulpw/visidata/issues/162 ?  might be useful in some cases for you.

**Comment by JPFrancoia** [comment]
Thanks! Are you the developer? I just tried it. It works, it displays the data, with a few problems though: it's slow (I mean moving up and down for example. My dataset has 20k entries), and creating the panda sheet at the beginning seems like sorcery. Is it/can it be integrated, so I would just have to do ```vdf.view(my_data_set)``` ?

**Comment by saulpw** [comment]
Yes, I'm the VisiData author.  It should not be slow with Pandas (or otherwise), but we made some major architecture changes in 1.3 and so something probably needs an optimization pass.  I will look into that and figure out what's wrong.  As for the sorcery creating the PandasSheet, I understand, it was just hacked in, but we expect to have a better interface for the next version.  I think something like vd.view(pandas_df) is very reasonable.
